// Generated by CoffeeScript 1.7.1
(function() {
  var demoText, getSeq, logoSettings, makeObj;

  demoText = ['HEXA'.split(''), 'FLIP'.split('')];

  logoSettings = {
    size: 120,
    margin: 8,
    fontSize: 82,
    perspective: 450
  };

  makeObj = function(a) {
    var i, o, v, _i, _len;
    o = {};
    for (i = _i = 0, _len = a.length; _i < _len; i = ++_i) {
      v = a[i];
      o['letter' + i] = a;
    }
    return o;
  };

  getSeq = function(a, reverse, random) {
    var i, len, o, p, v, _i, _len;
    o = {};
    len = a.length;
    for (i = _i = 0, _len = a.length; _i < _len; i = ++_i) {
      v = a[i];
      if (reverse) {
        p = len - i - 1;
      } else if (random) {
        p = Math.floor(Math.random() * len);
      } else {
        p = i;
      }
      o['letter' + i] = a[p];
    }
    return o;
  };

  document.addEventListener('DOMContentLoaded', function() {
    var action, hexaPhoto, hexaTime, i, logos, n, photoControls, textDemos, _fn, _i, _len, _ref;
    logos = document.getElementsByClassName('logo');
    textDemos = (function() {
      var _i, _results;
      _results = [];
      for (n = _i = 0; _i <= 1; n = ++_i) {
        _results.push(new HexaFlip(logos[n], makeObj(demoText[n]), logoSettings));
      }
      return _results;
    })();
    hexaPhoto = new HexaFlip(document.getElementById('photo-demo'), {
      photos: (function() {
        var _i, _results;
        _results = [];
        for (i = _i = 1; _i <= 18; i = ++_i) {
          _results.push("./demo/images/" + i + ".jpg");
        }
        return _results;
      })()
    }, {
      size: 400,
      horizontalFlip: true
    });
    photoControls = document.getElementById('photo-controls');
    _ref = ['flipBack', 'flip'];
    _fn = function(action) {
      return photoControls.children[i].addEventListener('click', (function() {
        return hexaPhoto[action]();
      }), false);
    };
    for (i = _i = 0, _len = _ref.length; _i < _len; i = ++_i) {
      action = _ref[i];
      _fn(action);
    }
    hexaTime = new HexaFlip(document.getElementById('time-demo'), null, {
      size: 150,
      fontSize: 100
    });
    setTimeout(function() {
      var _j;
      for (n = _j = 0; _j <= 1; n = ++_j) {
        textDemos[n].setValue(getSeq(demoText[n], true));
      }
      return null;
    }, 0);
    setTimeout(function() {
      var _j;
      for (n = _j = 0; _j <= 1; n = ++_j) {
        textDemos[n].setValue(getSeq(demoText[n]));
      }
      return null;
    }, 1000);
    setTimeout(function() {
      return setInterval(function() {
        var _j;
        for (n = _j = 0; _j <= 1; n = ++_j) {
          textDemos[n].setValue(getSeq(demoText[n], false, true));
        }
        return null;
      }, 3000);
    }, 5000);
    return setTimeout(function() {
      var hour, meridian, minute, now;
      now = new Date;
      hour = now.getHours();
      minute = now.getMinutes().toString();
      if (hour > 12) {
        hour = (hour - 12).toString();
        meridian = 'pm';
      } else {
        meridian = 'am';
        if (hour === 0) {
          hour = 12;
        }
        hour = hour.toString();
      }
      if (minute.length > 1) {
        minute = minute.substr(0, 1) + '0';
      } else {
        minute = '00';
      }
      return hexaTime.setValue({
        hour: hour,
        minute: minute,
        meridian: meridian
      });
    }, 1);
  }, false);

}).call(this);

//# sourceMappingURL=demo.map
